### PR TITLE
Milestone: Add user authentication with devise

### PR DESCRIPTION
**Pull request by Lancelot-SO**
### The following updates were made:

- setup user authentication with devise

### CODE REVIEW

**Review by ram1117 — CHANGES_REQUESTED** [review]
Hi @Lancelot-SO , when visiting the index page for the first time, login page has to be displayed. The user index is displayed instead. 

image

**Comment by Lancelot-SO** [comment]
> Hi @Lancelot-SO , when visiting the index page for the first time, login page has to be displayed. The user index is displayed instead. Please add styling to the sign in and sign up forms as we did in blogapp.
> 
> image

**Comment by Lancelot-SO** [comment]
it because you've already signed in

**Comment by ram1117** [comment]
i have not signed up. my users table is empty

**Review by ram1117 — APPROVED** [review]

**Pull request merged**
